---
- name: Provisioning Server
  hosts: all
  become: yes
  tasks:
    - name: Install NTP
      yum:
        name: ntp
        state: present
      when: ansible_facts['distribution'] == "CentOS"

    - name: Install NTP on Ubuntu
      apt:
        name: ntp
        state: present
      when: ansible_facts['distribution'] == "Ubuntu"

    - name: Start & enable NTP on Redhat
      service:
        name: ntpd
        state: started
        enabled: yes
      when: ansible_facts['os_family'] == "RedHat"

    - name: Start & enable NTP on Debian
      service:
        name: ntp
        state: started
        enabled: yes
      when: ansible_facts['os_family'] == "Debian"

    - name: Show facts avalaible on the system
      ansible.builtin.debug:
        var: ansible_facts  
