version: "3.8"

services:
  server:
    # image: nginx:stable-alpine
    build:
      context: .
      dockerfile: dockerfiles/nginx.dockerfile
    image: wanderingmono/docker-s8:laravel-php-web-nginx-v0.2-fixed-dpl
    ports:
      - '8000:80'
    volumes:
      - ./src:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
      - mysql

  php:
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
    image: wanderingmono/docker-s8:laravel-php-web-php-v0.2-fixed-dpl
    volumes:
      - ./src:/var/www/html:delegated
      # :delegated - is the optimization
      #if the container needs to write some data
      #to the folder back to the host machine
      #it will precces it in batches for better
      #performance
    # ports:
    #   - '3000:9000'

  mysql:
    platform: linux/x86_64
    image: mysql
    env_file:
      - ./env/mysql.env

  composer:
    build:
      context: ./dockerfiles
      dockerfile: composer.dockerfile
    image: wanderingmono/docker-s8:laravel-php-web-composer-v0.2-fixed-dpl
    volumes:
      - ./src:/var/www/html
  
  artisan:
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
    image: wanderingmono/docker-s8:laravel-php-web-artisan-v0.2-fixed-dpl
    volumes:
      - ./src:/var/www/html
    entrypoint: ["php", "/var/www/html/artisan"]
    # entrypoint disables RUN command in
    # dockerfile and executes itself command

  npm:
    image: node:14
    working_dir: /var/www/html
    entrypoint: ["npm"]
    volumes:
      - ./src:/var/www/html
