# docker-s7 ------------------------------------- 

#################################################
# nodejs image with app - docker-s7
# util-nodejs
#################################################
version: "3.8"
services:
  npm:
    build: ./
    stdin_open: true
    tty: true
    volumes:
      - ./:/app