apiVersion: apps/v1
kind: Deployment
metadata:
  name: second-app-deployment
  labels:
    group: example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: second-app
      tier: backend
    # matchExpressions:
    #   - {key: app, operator: In, values: [second-app, first-app]}
    # matchExpressions is more powerful and
    # complex method to work with labels and
    # selectors
  template:
    metadata:
      labels:
        app: second-app
        tier: backend
    spec:
      containers:
        - name: second-node
          image: wanderingmono/docker-s12:kub-first-app-v2
          imagePullPolicy: Always
          # imagePullPolicy: Never
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            periodSeconds: 10
            initialDelaySeconds: 5
        # to create multiple containers
        # - name: ...
        #   image: ...