---
# tasks file for post-install
- name: Install NTP
  yum:
    name: "{{item}}" # item name in loop
    state: present
  when: ansible_distribution == "CentOS"
  loop:
    - ntp
    - wget
    - git
    - zip
    - unzip  

- name: Install NTP on Ubuntu
  apt:
    name: "{{item}}"
    state: present
    update_cache: yes # apt update
  when: ansible_distribution == "Ubuntu"
  loop:
    - ntp
    - wget
    - git
    - zip
    - unzip  

- name: Start & enable NTP on Redhat
  service:
    name: ntpd
    state: started
    enabled: yes
  when: ansible_os_family == "RedHat"

- name: Start & enable NTP on Debian
  service:
    name: ntp
    state: started
    enabled: yes
  when: ansible_os_family == "Debian"

- name: Add group
  group:
    name: devops
    state: present

# Loop for users creation with variables from group_vars
- name: Add users
  user:
    name: "{{item}}"
    state: present
    groups: devops
  loop: "{{usernames}}"

- name: Banner file /etc/motd
  copy:
    content: "This {{ansible_distribution}} is managed by Ansible. \n"
    dest: /etc/motd

- name: Deploy NTP conf file for RedHat
  template:
    src: ntp_redhat.conf.j2
    dest: "{{ntp_path}}"
  when: ansible_os_family == "RedHat"
  notify:
    - Restart NTP on RedHat

- name: Deploy NTP conf file for Debian
  template:
    src: ntp_debian.conf.j2
    dest: "{{ntp_path}}"
  when: ansible_os_family == "Debian"
  notify:
    - Restart NTP on Debian

- name: Dir for dev data
  file:
    path: /opt/devdata
    state: directory
    mode: 0775

- name: Deploy dev data file
  copy:
    src: dev.txt
    dest: /opt/devdata/dev.txt
