---
- name: Webserver setup
  hosts: webservers
  become: true
  tasks:
    - name: Remove httpd and do autoremove
      ansible.builtin.yum:
        name: httpd
        state: absent
        autoremove: true

- name: DBserver setup
  hosts: dbservers
  become: true
  tasks:
    - name: Remove mariadb-server and do autoremove
      ansible.builtin.yum:
        name: mariadb-server
        state: absent
        autoremove: true
    